# Generated by Django 6.0.2 on 2026-02-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_adminactivitylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="can_revoke_admins",
            field=models.BooleanField(
                default=True, help_text="Can this admin revoke other admin privileges"
            ),
        ),
    ]
