# Generated by Django 6.0.2 on 2026-02-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_accounthistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="memorable_information",
            field=models.TextField(
                blank=True, help_text="Memorable information for account recovery"
            ),
        ),
    ]
