# Generated by Django 5.2.12 on 2026-03-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_accounthistory_id_alter_adminactivitylog_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounthistory',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Account Created'), ('REVOKED', 'Admin Privileges Revoked'), ('DELETED', 'Account Deleted'), ('REACTIVATED', 'Account Reactivated'), ('RESTRICTED', 'Account Restricted'), ('UNRESTRICTED', 'Account Unrestricted'), ('PASSWORD_RESET_INITIATED', 'Password Reset Initiated'), ('PASSWORD_RESET_COMPLETED', 'Password Reset Completed')], max_length=30),
        ),
    ]
